#!/bin/bash
export PATH=$PATH:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin

echo "========================================================"
echo "   Telegram Proxy (MTG) Diagnostic Tool"
echo "========================================================"

# 1. Check Binary
echo -n "Checking mtg binary... "
if [ -x "/opt/hiddify-manager/other/telegram/tgo/mtg" ]; then
    echo "✅ Found"
    /opt/hiddify-manager/other/telegram/tgo/mtg --version
else
    echo "❌ Missing or not executable!"
    echo "Attempting to install..."
    cd /opt/hiddify-manager/other/telegram/tgo/
    bash install.sh
    if [ -x "./mtg" ]; then
        echo "✅ Installation successful"
    else
        echo "❌ Installation failed. Please check internet connection or logs."
    fi
fi

# 2. Check Config
echo -n "Checking config file... "
if [ -f "/opt/hiddify-manager/other/telegram/tgo/mtg.toml" ]; then
    echo "✅ Found"
else
    echo "❌ Missing! (Will be generated by apply_configs.sh)"
fi

# 3. Check Service
echo "Checking service status..."
systemctl status mtproxy --no-pager

# 4. Check Logs
echo "========================================================"
echo "   Recent Logs (Last 20 lines)"
echo "========================================================"
tail -n 20 /opt/hiddify-manager/log/system/telegram.err.log

# 5. Check Port
echo "========================================================"
echo "   Listening Ports (1001)"
echo "========================================================"
netstat -tlnp | grep 1001
echo "Should be listening on 127.0.0.1:1001 (not 0.0.0.0)"

echo "========================================================"
echo "   Diagnostic Complete"
echo "========================================================"
