#!/bin/bash

# Read the contents of the file
toml_content=$(cat wgcf-account.toml)

# Extract the values using pattern matching
access_token=$(echo "$toml_content" | grep -oP "access_token = '[^']+'" | sed "s/access_token = '\([^']\+\)'/\1/")
device_id=$(echo "$toml_content" | grep -oP "device_id = '[^']+'" | sed "s/device_id = '\([^']\+\)'/\1/")
private_key=$(echo "$toml_content" | grep -oP "private_key = '[^']+'" | sed "s/private_key = '\([^']\+\)'/\1/")

# Prepare the new TOML content
new_toml="[Account]
Device     = $device_id
PrivateKey = $private_key
Token      = $access_token
Type       = plus
Name       = WARP
MTU        = 1420
"

# Write the new TOML content to a file
echo "$new_toml" > warp.conf

# ./warp-go --config=warp.conf --export-singbox=warp-singbox.json
# No need to run warp-go, we construct sing-box config directly or use wgcf profile

# Generate warp-singbox.json from wgcf-profile.conf if available or directly from params
# For now, let's assume we use the wireguard config generated by wgcf
wgcf generate -p wgcf-profile.conf

# Convert wgcf-profile.conf to sing-box format (simplified for now, ideally use a converter)
# OR rely on the fact that we might not need warp-go executable if we have keys. 
# But wait, run.sh line 24 uses warp-go to export singbox config. 
# If warp-go is missing, we can't do this. 
# Let's check if we can simply use the keys to build config.

# Actually, the user log showed "run.sh: line 24: ./warp-go: No such file or directory".
# We downloaded warp-go in install.sh, but maybe it failed or path is wrong.
# install.sh moves it to current dir: "mv /tmp/warp-go ."
# So ./warp-go should work IF install succeeded. 

# However, the service file uses: ExecStart=/opt/hiddify-manager/singbox/sing-box run -c warp-singbox.json
# So we DO need warp-singbox.json. 
# If ./warp-go fails, we can't get it easily without parsing. 

# Let's ensure warp-go is executable.
# ./warp-go --config=warp.conf --export-singbox=warp-singbox.json

# Parse wgcf-profile.conf to get private key and peer details
PRIVATE_KEY=$(grep 'PrivateKey' wgcf-profile.conf | cut -d' ' -f3)
PEER_PUBLIC_KEY=$(grep 'PublicKey' wgcf-profile.conf | cut -d' ' -f3)
PEER_ENDPOINT=$(grep 'Endpoint' wgcf-profile.conf | cut -d' ' -f3)
PEER_IP=${PEER_ENDPOINT%:*}
PEER_PORT=${PEER_ENDPOINT##*:}

# Create FULL sing-box config
cat <<EOF > warp-singbox.json
{
  "log": {
    "level": "info",
    "timestamp": true
  },
  "experimental": {
    "cache_file": {
      "enabled": true,
      "path": "warp-cache.db"
    }
  },
  "inbounds": [
    {
      "type": "socks",
      "tag": "socks-in",
      "listen": "127.0.0.1",
      "listen_port": 3000,
      "users": []
    }
  ],
  "outbounds": [
    {
      "type": "wireguard",
      "tag": "WARP",
      "server": "$PEER_IP",
      "server_port": $PEER_PORT,
      "local_address": [
        "172.16.0.2/32",
        "2606:4700:110:8f80:5553:6c97:546:9097/128"
      ],
      "private_key": "$PRIVATE_KEY",
      "peer_public_key": "$PEER_PUBLIC_KEY",
      "reserved": [0, 0, 0],
      "mtu": 1280
    },
    {
      "type": "direct",
      "tag": "direct"
    },
    {
      "type": "block",
      "tag": "block"
    },
    {
      "type": "dns",
      "tag": "dns-out"
    }
  ],
  "route": {
    "rules": [
      {
        "protocol": "dns",
        "outbound": "dns-out"
      },
      {
        "outbound": "WARP"
      }
    ],
    "auto_detect_interface": true,
    "final": "WARP"
  }
}
EOF


sed -i "s|2000|3000|g" warp-singbox.json
curl --connect-timeout 1 -s http://ipv6.google.com 2>&1 >/dev/null
if [ $? != 0 ]; then
sed -i 's/"local_address":\[[^]]*\]/"local_address":["172.16.0.2\/32"]/' warp-singbox.json

fi


# while read -r line; do
#     if [[ "$line" == \[*] ]]; then
#         section=${line#[}
#         section=${section%]}
#     elif [[ "$line" =~ ^[[:space:]]*([^[:space:]]+)[[:space:]]*=[[:space:]]*(.*)$ ]]; then
#         key=${BASH_REMATCH[1]}
#         value=${BASH_REMATCH[2]}
#         var="${section}_${key}"
#         value=$(echo "$value" | sed -e 's/^"//' -e 's/"$//')
#         export "$var"="$value"
#     fi
# done < "wgcf-profile.conf"


# cat > xray_warp_conf.json << EOM
#     {
#       "tag": "WARP",
#       "protocol": "wireguard",
#       "settings": {
#         "secretKey": "$Interface_PrivateKey",
#         "address": [
#           "172.16.0.2/32",
#           "$Interface_Address"
#         ],
#         "peers": [
#           {
#             "publicKey": "$Peer_PublicKey",
#             "endpoint": "$Peer_Endpoint"
#           }
#         ],
#         "reserved":[0, 0, 0], 
#         "mtu": 1280
#       }
#     }
# EOM


# peer_domain="${Peer_Endpoint%%:*}"
# peer_port="${Peer_Endpoint#*:}"

# cat > singbox_warp_conf.json << EOM
# {
#   "type": "wireguard",
#   "tag": "WARP",
#   "server": "$peer_domain",
#   "server_port": $peer_port,
#   "system_interface": false,

#   "local_address": [
#     "172.16.0.2/32",
#     "$Interface_Address"
#   ],
#   "private_key": "$Interface_PrivateKey",
#   "peer_public_key": "$Peer_PublicKey",
#   "reserved": [0, 0, 0],
#   "mtu": 1280
# }

# EOM
#"interface_name": "wg0",
#"pre_shared_key": "31aIhAPwktDGpH4JDhA8GNvjFXEf/a6+UaQRyOAiyfM=",
#"workers": 8,
# warp_conf=$(cat xray_warp_conf.json)
# warp_conf=$(echo "$warp_conf" | tr '\n' ' ')
# escaped_warp_conf=$(printf '%s\n' "$warp_conf" | sed -e 's/[\/&]/\\&/g')
# sed "s|//hiddify_warp|$escaped_warp_conf|g"  xray_demo.json.template > xray_demo.json

# singbox_warp_conf=$(cat singbox_warp_conf.json)
# singbox_warp_conf=$(echo "$singbox_warp_conf" | tr '\n' ' ')
# escaped_singbox_warp_conf=$(printf '%s\n' "$singbox_warp_conf" | sed -e 's/[\/&]/\\&/g')
# sed "s|//hiddify_warp|$escaped_singbox_warp_conf|g"  singbox_demo.json.template > singbox_demo.json
# sed "s|//hiddify_warp|$escaped_singbox_warp_conf|g"  warp-singbox.json.template > warp-singbox.json



# xray -c xray_demo.json >/dev/null  &
# pid=$!
# sleep 3
# curl -x socks://127.0.0.1:1230 www.ipinfo.io
# curl -x socks://127.0.0.1:1230 http://ip-api.com?fields=message,country,countryCode,city,isp,org,as,query
# if [ $? != 0 ];then
#     rm xray_warp_conf.json
# else
#    echo ""
#    echo "==========WARP is working=============="
# fi
# kill -9 $pid



# echo "Testing singbox warp"

# sing-box run -c singbox_demo.json >/dev/null  &
# pid=$!
# sleep 3
# curl -x socks://127.0.0.1:1231 www.ipinfo.io
# curl -x socks://127.0.0.1:1231 http://ip-api.com?fields=message,country,countryCode,city,isp,org,as,query
# if [ $? != 0 ];then
#     rm singbox_warp_conf.json
# else
#    echo ""
#    echo "==========WARP is working=============="
# fi
# kill -9 $pid



systemctl reload hiddify-warp.service
systemctl start  hiddify-warp.service
#systemctl status hiddify-warp.service

sleep 5
echo "Testing singbox warp"


curl -s -x socks://127.0.0.1:3000 --connect-timeout 4 www.ipinfo.io >/dev/null 2>&1
curl -s -x socks://127.0.0.1:3000 --connect-timeout 4 http://ip-api.com?fields=message,country,countryCode,city,isp,org,as,query
if [ $? != 0 ];then
    echo "WARP is not working"
else
   echo ""
   echo "==========WARP is working=============="
fi

# echo "Remaining..."
# bash check-quota.sh
# fi