source /opt/hiddify-manager/common/utils.sh

# Ensure logs are readable by hiddify-panel
touch /opt/hiddify-manager/log/singbox.log
touch /opt/hiddify-manager/log/system/singbox.log
chmod 644 /opt/hiddify-manager/log/singbox.log 2>/dev/null || true
chmod 644 /opt/hiddify-manager/log/system/singbox.log 2>/dev/null || true
chown hiddify-panel:root /opt/hiddify-manager/log/singbox.log 2>/dev/null || true

ln -sf $(pwd)/hiddify-singbox.service /etc/systemd/system/hiddify-singbox.service 2>/dev/null || true
systemctl enable hiddify-singbox.service 2>/dev/null || true

# Only set permissions if config file exists (generated by jinja)
if [ -f "configs/01_api.json" ]; then
    set_files_in_folder_readable_to_hiddify_common_group configs/01_api.json
fi
# curl -s -x socks://127.0.0.1:3000 http://ip-api.com?fields=message,country,countryCode,city,isp,org,as,query

# Start singbox service
if systemctl list-unit-files hiddify-singbox.service &>/dev/null; then
	if systemctl is-active --quiet hiddify-singbox.service; then
		# watashi v12.2.105: a reload only sends SIGHUP, so a core that was
		# replaced on disk keeps running its old code and refuses every inbound
		# type it does not know. that turns one new inbound into a frozen
		# config for every protocol. compare the running binary with the one on
		# disk and restart when they differ.
		ws_sb_pid=$(systemctl show hiddify-singbox.service -p MainPID --value 2>/dev/null)
		ws_sb_stale=no
		if [ -n "$ws_sb_pid" ] && [ "$ws_sb_pid" != "0" ]; then
			ws_sb_running=$(readlink -f "/proc/$ws_sb_pid/exe" 2>/dev/null)
			ws_sb_ondisk=$(readlink -f /opt/hiddify-manager/singbox/sing-box 2>/dev/null)
			if [ -n "$ws_sb_running" ] && [ "$ws_sb_running" != "$ws_sb_ondisk" ]; then
				ws_sb_stale=yes
			elif [ -n "$ws_sb_running" ] && [ ! -e "$ws_sb_running" ]; then
				ws_sb_stale=yes
			elif [ /opt/hiddify-manager/singbox/sing-box -nt "/proc/$ws_sb_pid" ]; then
				ws_sb_stale=yes
			fi
		fi
		# watashi v12.2.105: never hand a broken config to the running core. if
		# the core's own validator rejects it, say so loudly and keep serving
		# the config that still works instead of failing in silence.
		if ! /opt/hiddify-manager/singbox/sing-box check -C /opt/hiddify-manager/singbox/configs >/tmp/watashi-singbox-check.log 2>&1; then
			echo "watashi: the sing-box config was rejected by the core, not reloading" >&2
			cat /tmp/watashi-singbox-check.log >&2
		elif [ "$ws_sb_stale" = "yes" ]; then
			echo "watashi: the core binary changed, restarting instead of reloading" >&2
			systemctl restart hiddify-singbox.service
		else
			systemctl reload hiddify-singbox.service 2>/dev/null || systemctl restart hiddify-singbox.service
		fi
	else
		systemctl start hiddify-singbox.service 2>/dev/null || true
	fi
else
	echo "hiddify-singbox.service not installed yet"
fi

# watashi v12.2.100: the shadowsocks port was opened by common/run.sh only,
# and that script is skipped on the light user save path, so a shadowsocks
# switched on from the panel kept answering nothing until a full reinstall
# finally opened the port. the ports this core listens on are synced here
# every time the core is applied, which is what that reinstall really did.
ws_sync_core_ports() {
    local cj=/opt/hiddify-manager/current.json
    [ -f "$cj" ] || return 0
    command -v jq >/dev/null 2>&1 || return 0
    local changed=0 en port
    en=$(jq -r '.chconfigs["0"].shadowsocks2022_enable // false' "$cj")
    port=$(jq -r '.chconfigs["0"].shadowsocks2022_port // empty' "$cj")
    if [ "$en" == "true" ] && [ -n "$port" ] && [ -z "${port//[0-9]/}" ]; then
        allow_port "tcp" "$port"
        allow_port "udp" "$port"
        changed=1
    fi
    if [ "$(jq -r '.chconfigs["0"].hysteria_enable // false' "$cj")" == "true" ]; then
        for port in $(jq -r '.domains[]?.internal_port_hysteria2 // empty' "$cj"); do
            if [ -n "$port" ] && [ "$port" != "0" ] && [ -z "${port//[0-9]/}" ]; then
                allow_port "udp" "$port"
                changed=1
            fi
        done
    fi
    if [ "$(jq -r '.chconfigs["0"].tuic_enable // false' "$cj")" == "true" ]; then
        for port in $(jq -r '.domains[]?.internal_port_tuic // empty' "$cj"); do
            if [ -n "$port" ] && [ "$port" != "0" ] && [ -z "${port//[0-9]/}" ]; then
                allow_port "udp" "$port"
                changed=1
            fi
        done
    fi
    # watashi v12.2.101: anytls and snell listen on tcp ports of their own.
    # they are not in tls_ports or http_ports, so allow_apps_ports never
    # opens them and every handshake would time out on a box whose firewall
    # is on. the ports are read from the very same current.json the
    # templates render from, so the firewall cannot drift from the config.
    for key in anytls snell; do
        if [ "$(jq -r --arg k "${key}_enable" '.chconfigs["0"][$k] // false' "$cj")" == "true" ]; then
            for port in $(jq -r --arg k "internal_port_$key" '.domains[]?[$k] // empty' "$cj"); do
                if [ -n "$port" ] && [ "$port" != "0" ] && [ -z "${port//[0-9]/}" ]; then
                    allow_port "tcp" "$port"
                    changed=1
                fi
            done
        fi
    done
    if [ "$changed" == "1" ]; then
        save_firewall
    fi
    return 0
}
ws_sync_core_ports
