source /opt/hiddify-manager/common/utils.sh
ln -sf $(pwd)/hiddify-singbox.service /etc/systemd/system/hiddify-singbox.service 2>/dev/null || true
systemctl enable hiddify-singbox.service 2>/dev/null || true

# Only set permissions if config file exists (generated by jinja)
if [ -f "configs/01_api.json" ]; then
    set_files_in_folder_readable_to_hiddify_common_group configs/01_api.json
fi
# curl -s -x socks://127.0.0.1:3000 http://ip-api.com?fields=message,country,countryCode,city,isp,org,as,query

# Start singbox service
if systemctl list-unit-files hiddify-singbox.service &>/dev/null; then
	if systemctl is-active --quiet hiddify-singbox.service; then
		systemctl reload hiddify-singbox.service 2>/dev/null || systemctl restart hiddify-singbox.service
	else
		systemctl start hiddify-singbox.service 2>/dev/null || true
	fi
else
	echo "hiddify-singbox.service not installed yet"
fi
